version: '3.8'

services:
  dramatiq-worker:
    image: microstack-dramatiq:0.1
    command: /worker.sh 
    restart: always
    deploy:
      mode: replicated
      replicas: 2
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - LOG_FOLDER=/data
    network_mode: host
    volumes:
      - /scripts:/scripts
      - /data/dramatiq:/data
 