version: '3.8'

services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --loglevel warning --requirepass $REDIS_PASSWORD
    restart: always
    expose:
      - "6379"
#    ports:
#      - target: 6379
#       published: 6379
#        protocol: tcp
#        mode: host
    volumes:
      - /data/redis:/data
    environment:
      - REDIS_REPLICATION_MODE=master